language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
deploy:
  provider: heroku
  api_key:
    secure: CNCFBOBwLtur8WCQAKQyL6bfNsxtjc//9VxLojGGFZuyaRuWmLcCXBdKce5znTS8hABxdHjC4OyQCLDeOKMozkoxd4WC96DonOpy9JCgUxljTysxasOSusLYNzsrsdPYzyOA7ll4uPr77BfVOUb6U2KjHbYAg5wmx8GLCG+6etc=
  app: me-app-qa
  on:
    repo: pedramphp/me-app
