language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
deploy:
  provider: heroku
  api_key:
    secure: FCQee/Xff/apvt0x+V+4NMGABpuxGWbPl53MTwPwKhSy6Zv+rfgDq0WauT183TxggIBRRi6Rp9iBbUh+HBdjS0ytCzTvpMwyDmv9YYQzzilDGeMUuYKnYGQkaStd+wMBXWQUngCqQqHocmLOJQ++X4UwmMtBo0T2Ni0cogPccBM=
  app: me-app-qa
  on:
    repo: pedramphp/me-app
